### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by jonascarpay** [purenix-org/purenix#10]
At some point, we'll have to do a release. Tentative checklist:

- [x] Fix outstanding issues
  - [x] #7 
  - [x] #6 
  - [x] #15 
  - [x] #19 
- [x] Pick a version number and version numbering scheme. I think we can just go for `1.0` (_edit_: we decided to go for `1.0`.  The versioning scheme is described in the changelog.)
- [x] #29 
- [x] Upload to Hackage (_edit_: uploaded as https://hackage.haskell.org/package/purenix-1.0)
- [X] Advertise (probably just on the Nix discourse? maybe also PS discourse?) (_edit_: posted as https://discourse.nixos.org/t/purenix-nix-backend-for-purescript/15756)
- [ ] add a default.nix for non-flake users?
- [x] @cdepillabout thinks we should write a blog post. Who writes it, and what does it contain? (_edit_: I've started writing this: https://functor.tokyo/blog/2022-01-03-purenix)

**Comment by cdepillabout** [comment]
another possible release item: Get `purenix` compiling in nixpkgs, and switch our `flake.nix` over to building `purenix` with the Haskell stuff in Nixpkgs instead of haskell.nix.  The benefit of doing this is that users won't have to opt-in to using the IOHK caches in order to try out purenix.

The downside of doing this is that the Haskell stuff in Nixpkgs is currently on LTS-18, while the PureScript repo is still on LTS-17 (if I remember correctly).  It might take a little work getting PureScript building in Nixpkgs.

**Comment by cdepillabout** [comment]
This is mostly done, so I'll go ahead and close this issue.

> add a default.nix for non-flake users?

This is the only thing we don't have yet, although it should be easy to add if someone asks for it.  I think we can probably just ignore this for now until someone sends a PR or creates a PR specifically asking about it.
