### ISSUE TITLE
add binary cache

### ISSUE THREAD

**Issue by DavHau** [purenix-org/purenix#31]
Just loading the devShell and it needs to build a lot of stuff.
I see there is already a cachix github action but commented out. Maybe consider re-adding it?

**Comment by cdepillabout** [comment]
@DavHau We're currently thinking of trying to get PureNix building in Nixpkgs, so that you'd be able to just get it from the Nix cache.

The problem of using cachix is that we're currently using [haskell.nix](https://input-output-hk.github.io/haskell.nix/) to build PureNix, and there is a whole bunch of stuff in the build-time closure when you use haskell.nix.  I haven't actually checked, but I am somewhat worried the build-time closure is actually over the 10G you get from Cachix.

If you add the IOHK cache, you will hopefully be able to at least get some dependencies stuff from their cache, so it won't take multiple hours to build everything (maybe just a couple tens of minutes): https://input-output-hk.github.io/haskell.nix/tutorials/getting-started/#setting-up-the-binary-cache

**Comment by jonascarpay** [comment]
> I haven't actually checked, but I am somewhat worried the build-time closure is actually over the 10G you get from Cachix.

My personal cachix, that I mainly use for https://github.com/jonascarpay/template-haskell actually manages to serve a fairly complete haskell.nix-based cabal project closure without issues.
I'm not sure if it's possible, but maybe we can make a cachix for `purenix-org`? I fully agree that we should get PureNix in nixpkgs asap, but cachix might be a good stopgap solution.

**Comment by jonascarpay** [comment]
1. [x] https://github.com/purescript/purescript/pull/4199
2. [ ] https://github.com/NixOS/nixpkgs/pull/145310
3. [ ] PureNix in Nix as simple cabal package

Is that correct @cdepillabout?

**Comment by cdepillabout** [comment]
@jonascarpay Yes, that is correct!
